name: 发布

on:
  push:
    tags:
      - "v*"

jobs:
  publish-github-pkg:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"

      - name: 发布 @huvubb/code-poet-cli
        working-directory: code-poet-cli
        run: |
          npm pkg set name="@huvubb/code-poet"
          npm pkg set repository="https://github.com/huvubb/code-poet"
          npm version ${{ github.ref_name }} --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
